export const ROLES = ['INVESTOR', 'OFFICER', 'ADMIN'] as const;
export const ONBOARDING_STATUSES = ['REGISTERED', 'PAN_SUBMITTED', 'DOCUMENT_UPLOADED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'REUPLOAD_REQUIRED'] as const;
export const DOCUMENT_TYPES = ['AADHAAR_FRONT', 'AADHAAR_BACK', 'PAN_CARD', 'PHOTO'] as const;
export const DOCUMENT_STATUSES = ['PENDING', 'VERIFIED', 'REJECTED'] as const;
export const VERIFICATION_STATUSES = ['PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'REUPLOAD_REQUIRED'] as const;
